openapi: 3.1.0
info:
  title: Create a new post
  description: REST API to create a new post.
  version: 'v1.0'
servers:
 - url: http://localhost:8080
paths:
  /createNewPost:
    post:
      summary: create a new post
      requestBody:
        description: new post request parameters
        required: true
        content:
          application/json: 
            schema: 
              $ref: '#/components/schemas/RecipeRequest'
      responses:
        "200":
          description: request successfully sent
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/RecipeResponse"
components:
  schemas:
    RecipeRequest:
      type: object
      properties:
        theme:
          type: string
          examples: 
            - feed
        title:
          type: string
          examples: 
            - my new pork ribs recipe
        description:
          type: string
          examples: 
            - Indulge in the homey warmth of our succulent herb-crusted pork chops, a dish that promises to delight your palate and grace your table with its rustic charm.
        tags:
          type: array
          items: 
            type: string
            examples: 
              - bakedfood
        image:
          type: string
          format: byte
          examples: 
            - 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADYAAABmCAYAAACAy2IqAAAKq2lD'
        ingredients:
          type: array
          items: 
            type: string
            examples: 
              - pork
        
    RecipeResponse:
      type: object
      properties:
        statusCode:
          type: string
          examples:
            - 200
        statusMsg:
          type: string
          examples: 
            - Successfully posted
        recipeList:
          type: array
          items: 
            type: object
            properties:
              author:
                type: string
                examples: 
                  - henryChen
              title:
                type: string
                examples: 
                  - my new pork ribs recipe
              description:
                type: string
                examples: 
                  - Indulge in the homey warmth of our succulent herb-crusted pork chops, a dish that promises to delight your palate and grace your table with its rustic charm.
              tags:
                type: array
                items: 
                  type: string
                  examples: 
                    - bakedfood
              image:
                type: string
                examples: 
                  - https://examples/food.png
              ingredients:
                type: array
                items: 
                  type: string
                  examples: 
                    - pork

        
