openapi: 3.1.0
info:
  title: Login
  description: REST API to login.
  version: 'v1.0'
servers:
 - url: http://localhost:8080
paths:
  /login:
    post:
      summary: login
      requestBody:
        description: login
        required: true
        content:
          application/json: 
            schema: 
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: request successfully sent
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/LoginResponse"
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          examples: 
            - henryChen
        password:
          type: string
          examples: 
            - happy6150
        
    LoginResponse:
      type: object
      properties:
        statusCode:
          type: string
          examples:
            - 200
        statusMsg:
          type: string
          examples: 
            - login success
        UserInfo:
          type: object
          properties: 
            userId:
              type: string
              examples: 
                - abc12345
            username:
              type: string
              examples: 
                - henryChen
            email:
              type: string
              examples: 
                - henrychener@gmail.com
