/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminRole;

import Hospital.Hospital;
import Hospital.Organization.AdminOrganization;
import Hospital.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.DoctorRole.AppointmentScheduleJPanel;

/**
 *
 * @author josie
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Hospital hospital;
    /**
     * Creates new form AdminWorkAreaJPanel
     */

    public AdminWorkAreaJPanel(JPanel userProcessContainer, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.hospital = hospital;
        setSize(1500, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPurchaseRequest = new javax.swing.JButton();
        btnAppointmentRequest = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel1.setText("Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        btnPurchaseRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnPurchaseRequest.setText("Purchase Request");
        btnPurchaseRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseRequestActionPerformed(evt);
            }
        });
        add(btnPurchaseRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 301, 60));

        btnAppointmentRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnAppointmentRequest.setText("Appointment Schedule Request");
        btnAppointmentRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentRequestActionPerformed(evt);
            }
        });
        add(btnAppointmentRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, 60));

        btnCreateUser.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnCreateUser.setText("Create User ");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });
        add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 301, 60));

        btnReport.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnReport.setText("Report & Analysis");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 300, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin-workarea.jpeg"))); // NOI18N
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1500, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPurchaseRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseRequestActionPerformed
        // TODO add your handling code here:
        PurchaseRequestJPanel prj = new PurchaseRequestJPanel(userProcessContainer, hospital);
        userProcessContainer.add("PurchaseRequestJPanel", prj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPurchaseRequestActionPerformed

    private void btnAppointmentRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentRequestActionPerformed
        // TODO add your handling code here:
        AppointmentScheduleRequestJPanel amsrjp = new AppointmentScheduleRequestJPanel(userProcessContainer, hospital);
        userProcessContainer.add("AppointmentScheduleRequestJPanel", amsrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAppointmentRequestActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        CreateUserJPanel cuj = new CreateUserJPanel(userProcessContainer, hospital);
        userProcessContainer.add("CreateUserJPanel", cuj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        ReportJPanel cuj = new ReportJPanel(userProcessContainer, hospital);
        userProcessContainer.add("ReportJPanel", cuj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointmentRequest;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnPurchaseRequest;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
