/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminRole;

import Hospital.Appointment.Appointment;
import Hospital.Doctor.Doctor;
import Hospital.Hospital;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Ingrid
 */
public class DoctorMostAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorMostAppointmentJPanel
     */
    JPanel workArea;
    Hospital hospital;
    
    public DoctorMostAppointmentJPanel(JPanel workArea, Hospital hospital) {
        initComponents();
        this.workArea = workArea;
        this.hospital = hospital; 
        
        setSize(1500, 1000);
        populateTable();
        setTableSoter();
        
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblDoctorList.getModel();

        model.setRowCount(0);
        int j=0;
        for (Appointment ap : hospital.getAppointmentHistory().getAppointmentList())  {
            String doctorID = ap.getDoctorID();
            String doctorName = hospital.getDoctorHistory().findDoctor(doctorID).getName();
            String department = ap.getDepartment();
                       
            boolean duplicateFlag=false;
            Object[] row = new Object[3];
            if (j==0)  {
                row[0] = department;
                row[1] = doctorName;
                row[2] = j+1;
                model.addRow(row);
            }
            
            j++;
            for (int i=0 ; i<model.getRowCount(); i++) {
                String selectedDepartment = (String) model.getValueAt(i,0);
                String selectedDoctorName = (String) model.getValueAt(i,1);
                if (selectedDepartment.equals(department)) {
                    if (selectedDoctorName.equals(doctorName)) {                            
                        model.setValueAt(j, i, 2);
                        duplicateFlag=true;
                        break;
                    }   
                }
            } 

            if (duplicateFlag==false) {
                j=1;
                row[0] = department;
                row[1] = doctorName;
                row[2] = j;
                model.addRow(row);
            }
        }  
          
    }
    
    public void setTableSoter(){
        
        tblDoctorList.setAutoCreateRowSorter(true);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblDoctorList.getModel());  
        
        List <RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>();  
        sortKeys.add(new RowSorter.SortKey(2, SortOrder.DESCENDING));        
        sorter.setSortKeys(sortKeys);   
        tblDoctorList.setRowSorter(sorter); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctorList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDoctorList.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        tblDoctorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Department", "Doctor Name", "Total Number of Appointment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDoctorList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 687, 259));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("The Most booked doctors");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 1488, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 37));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VWH_Illustration_What-is-a-Fistula_Illustrator_Laura-Porter_No-Text_Final-74dde8ca763c43e8ba76d647ec34b8a0.jpeg"))); // NOI18N
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1500, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDoctorList;
    // End of variables declaration//GEN-END:variables
}
