/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminRole;

import Hospital.Appointment.Appointment;
import Hospital.Hospital;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Ingrid
 */
public class MostPeopleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MostPeopleJPanel
     */
    JPanel workArea;
    Hospital hospital;
    public MostPeopleJPanel(JPanel workArea, Hospital hospital) {
        initComponents();
        setSize(1500, 1000);
        this.workArea = workArea;
        this.hospital = hospital; 
        populateTable();
        setTableSorter();
        
//        if (tblPeople.getRowCount()>0){       
//            txtdepartment.setText((String)tblPeople.getValueAt(0,0));
//        }
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPeople.getModel();

        model.setRowCount(0);
        int j=0;
        ArrayList<String> childNameList= new ArrayList<>() ;     
        for (Appointment ap : hospital.getAppointmentHistory().getAppointmentList())  {
            String childName = ap.getChildName();            
            String department = ap.getDepartment();
             
            boolean duplicateFlag=false;
            
            Object[] row = new Object[2];
            if (j==0)  {
                row[0] = department;                
                row[1] = j+1;
                model.addRow(row);
                childNameList.add(childName);
            }            
            j++;
            for (int i=0 ; i<model.getRowCount(); i++) {
                String selectedDepartment = (String) model.getValueAt(i,0);
                
                if (selectedDepartment.equals(department)) {
                    boolean duplicateName=false;
                    for (int n=0 ; n < childNameList.size(); n++) {
                        String selectedChildName = childNameList.get(n);
                        if ((selectedChildName.equals(childName))) { 
                            duplicateName=true;
                            break;
                        }                           
                    }
                    if (duplicateName==false) {
                        childNameList.add(childName);
                        model.setValueAt(childNameList.size(), i, 1);
                    }
                    duplicateFlag=true;
                    break;
                }
            } 

            if (duplicateFlag==false) {
                j=1;
                childNameList.clear();
                row[0] = department;
                row[1] = j;
                model.addRow(row);
                childNameList.add(childName);
            }
        }  
          
    }
    
    public void setTableSorter(){
        
        tblPeople.setAutoCreateRowSorter(true);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblPeople.getModel());  
        
        List <RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>();  
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.DESCENDING));        
        sorter.setSortKeys(sortKeys);   
        tblPeople.setRowSorter(sorter); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeople = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Number of visits for each department");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 1494, -1));

        tblPeople.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        tblPeople.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Department", "Total Number of patients"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPeople);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 564, 336));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 37));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VWH_Illustration_What-is-a-Fistula_Illustrator_Laura-Porter_No-Text_Final-74dde8ca763c43e8ba76d647ec34b8a0.jpeg"))); // NOI18N
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1500, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPeople;
    // End of variables declaration//GEN-END:variables
}
