/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminRole;

import Hospital.Enterprise.Manufacturer;
import Hospital.Hospital;
import Hospital.PurchasingOfficer.PurchasingOfficer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josie
 */
public class PurchaseRequestJPanel extends javax.swing.JPanel {

    JPanel workArea;
    Hospital hospital;
    /**
     * Creates new form PurchaseRequestJPanel
     */

    PurchaseRequestJPanel(JPanel userProcessContainer, Hospital hospital) {
        initComponents();
        
        setSize(1500, 1000);
        this.workArea = userProcessContainer;
        this.hospital = hospital; 
        
        purchaseTable();
        txtBudget.setText(Integer.toString(budget()));
    }
    
    public int budget(){
        int origin=1000000;
        int calculate=origin;
        for(PurchasingOfficer purchasingOfficer :hospital.purchasingOfficerHistory.getPurchasingOfficerList()){
            String status=purchasingOfficer.getStatus();

            if(status=="Approved"){
                int tempPrice = purchasingOfficer.getPrice();
                int tempQuantity = purchasingOfficer.getQuantity();
                int tempTotal=tempPrice * tempQuantity;
                calculate=calculate-tempTotal;
                if(calculate<0){
                    JOptionPane.showMessageDialog(null,"Budget Deficit!","Warning",JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        
        return calculate;
    }

    public void purchaseTable(){
        DefaultTableModel dtm=(DefaultTableModel) tblRequest.getModel();
        dtm.setRowCount(0);
        for(PurchasingOfficer purchasingOfficer :hospital.purchasingOfficerHistory.getPurchasingOfficerList()){
            String status=purchasingOfficer.getStatus();
            if(status=="Verified" || status=="Rejected"){
                Object[] row =new Object[8];
                row[0]=purchasingOfficer.getDate();
                row[1]=purchasingOfficer.getDoctorName();
                row[2]=purchasingOfficer.getManufactureName();
                row[3]=purchasingOfficer.getProductName();
                row[4]=purchasingOfficer.getQuantity();
                row[5]=purchasingOfficer.getPrice();
                row[6]=purchasingOfficer.getMessage();
                row[7]=purchasingOfficer.getStatus();

                dtm.addRow(row);
            
            }
        }
//            if(status=="Approved"){
//                Object[] row =new Object[8];
//                row[0]=purchasingOfficer.getDate();
//    //            row[1]=purchasingOfficer.getDoctorName();
//                row[2]=purchasingOfficer.getManufactureName();
//                row[3]=purchasingOfficer.getProductName();
//                row[4]=purchasingOfficer.getQuantity();
//                row[5]=purchasingOfficer.getPrice();
//                row[6]=purchasingOfficer.getMessage();
//                row[7]=purchasingOfficer.getStatus();
//
//                dtm.addRow(row);
//            }
            
//        System.out.println("111");
//        DefaultTableModel dtm=(DefaultTableModel) tblRequest.getModel();
//        dtm.setRowCount(0);
//        for(PurchasingOfficer purchasingOfficer :hospital.purchasingOfficerHistory.getPurchasingOfficerList()){
//            System.out.println("000");
//            System.out.println(purchasingOfficer.getProductName());
//            if(purchasingOfficer.getStatus().equals("Verified")){
//                
//               Object[] row =new Object[7];
//                row[0]=purchasingOfficer.getDate();
//    //            row[1]=purchasingOfficer.getDoctorName();
//                row[2]=purchasingOfficer.getManufactureName();
//                row[3]=purchasingOfficer.getProductName();
//                row[4]=purchasingOfficer.getQuantity();
//                row[5]=purchasingOfficer.getPrice();
//                row[6]=purchasingOfficer.getMessage();
//                row[7]=purchasingOfficer.getStatus();
//
//                dtm.addRow(row);
//            }
//        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        txtBudget = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRequest.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Doctor", "Manufacturer", "Product", "Quantity", "Price / Per", "Message", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 173, 1393, 443));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Purchase Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 1500, -1));

        btnApprove.setBackground(new java.awt.Color(204, 255, 204));
        btnApprove.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 634, 120, 42));

        txtBudget.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        txtBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBudgetActionPerformed(evt);
            }
        });
        add(txtBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 634, 173, 42));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Remain Budget :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 642, -1, -1));

        btnBack1.setBackground(new java.awt.Color(0, 0, 0));
        btnBack1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 37));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pattern.png"))); // NOI18N
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1500, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblRequest.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{

            String date = (String) tblRequest.getValueAt(selectedRow, 0);
            String manufacturerName= (String) tblRequest.getValueAt(selectedRow, 2);
            String productName= (String) tblRequest.getValueAt(selectedRow, 3);
            int quantity=(int) tblRequest.getValueAt(selectedRow, 4);
            int a=0;
            
            for(Manufacturer manufacturer:hospital.manufacturerDirectory.getManufacturerDirectory()){
                if(manufacturerName.equals(manufacturer.getManufactureName())&& productName.equals(manufacturer.getProductName())){
                    int remain=manufacturer.getQuantity();
                    remain=remain-quantity;
                   
                    if(remain<0){
                        a=1;
                        JOptionPane.showMessageDialog(null,"The quantity is insufficient.","Information",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        manufacturer.setQuantity(remain);
                    }
                    
                }
            }
            
            for(PurchasingOfficer test :hospital.purchasingOfficerHistory.getPurchasingOfficerList()){
                if(date.equals(test.getDate())){
                    if(a==0){
                        test.setStatus("Approved");
                        test.setResultMessage("");
                        JOptionPane.showMessageDialog(null,"The request is Approve now!","Information",JOptionPane.INFORMATION_MESSAGE);
                        purchaseTable();
                        txtBudget.setText(Integer.toString(budget()));
                    }
                    else{
                        test.setStatus("Rejected");
                        test.setResultMessage("The quantity is insufficient.");
                    }

                }
            }
            
            purchaseTable();
            txtBudget.setText(Integer.toString(budget()));
            
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void txtBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBudgetActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField txtBudget;
    // End of variables declaration//GEN-END:variables
}
