/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminRole;

import Hospital.Hospital;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ingrid
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Report
     */
    
    JPanel userProcessContainer;
    Hospital hospital;
    
    public ReportJPanel(JPanel userProcessContainer, Hospital hospital) {
        initComponents();
        
        setSize(1500, 1000);
        this.userProcessContainer = userProcessContainer;
        this.hospital = hospital;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTimeSlot = new javax.swing.JButton();
        btnMostPeople = new javax.swing.JButton();
        btnMostDoctorAppointment = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTimeSlot.setBackground(new java.awt.Color(0, 0, 0));
        btnTimeSlot.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnTimeSlot.setForeground(new java.awt.Color(255, 255, 255));
        btnTimeSlot.setText("Which time slot is the busiest?");
        btnTimeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeSlotActionPerformed(evt);
            }
        });
        add(btnTimeSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 360, 70));

        btnMostPeople.setBackground(new java.awt.Color(0, 0, 0));
        btnMostPeople.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnMostPeople.setForeground(new java.awt.Color(255, 255, 255));
        btnMostPeople.setText("Which department has the most patient?");
        btnMostPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostPeopleActionPerformed(evt);
            }
        });
        add(btnMostPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 450, 70));

        btnMostDoctorAppointment.setBackground(new java.awt.Color(0, 0, 0));
        btnMostDoctorAppointment.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnMostDoctorAppointment.setForeground(new java.awt.Color(255, 255, 255));
        btnMostDoctorAppointment.setText("Which doctor has the most appointments?");
        btnMostDoctorAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostDoctorAppointmentActionPerformed(evt);
            }
        });
        add(btnMostDoctorAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 500, 70));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 37));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GettyImages-683290612-591efa845f9b58f4c0dc58a9.jpeg"))); // NOI18N
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1500, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostPeopleActionPerformed
        // TODO add your handling code here:
        MostPeopleJPanel cuj = new MostPeopleJPanel(userProcessContainer, hospital);
        userProcessContainer.add("MostPeopleJPanel", cuj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMostPeopleActionPerformed

    private void btnMostDoctorAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostDoctorAppointmentActionPerformed
        // TODO add your handling code here:
        DoctorMostAppointmentJPanel cuj = new DoctorMostAppointmentJPanel(userProcessContainer, hospital);
        userProcessContainer.add("DoctorMostAppointmentJPanel", cuj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMostDoctorAppointmentActionPerformed

    private void btnTimeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeSlotActionPerformed
        // TODO add your handling code here:
        TimeSlotJPanel tsj = new TimeSlotJPanel(userProcessContainer, hospital);
        userProcessContainer.add("TimeSlotJPanel", tsj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTimeSlotActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMostDoctorAppointment;
    private javax.swing.JButton btnMostPeople;
    private javax.swing.JButton btnTimeSlot;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
