/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Uni.Course.Course;
import Uni.Professor.Professor;
import Uni.Student.Student;
//import uni.course.courseHistory;
import Uni.Uni;
import java.util.ArrayList;


/**
 *
 * @author Ingrid
 */
public class ProfessorCurrentCourseJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private Uni uni;
    private Course course;
    private Professor professor;
    /**
     * Creates new form CurrentClassJPanel
     */
//    public ProfessorCurrentCourseJPanel() {
//        initComponents();
//    }

//    ProfessorCurrentCourseJPanel(JPanel workArea, courseHistory courseHistory) {
      ProfessorCurrentCourseJPanel(JPanel workArea, Professor professor, Uni uni) {
        initComponents();
         this.workArea=workArea;
         this.uni=uni;
         this.professor=professor;
//         this.course=course;
//         this.courseHistory=courseHistory;
//         currentCourseTable();
    }
    
    private void currentCourseTable(){ 
        String semester=btnSemester.getSelectedItem().toString();
        String professorUserID=professor.getProfessorUserID().toString();
        
        Course existCourse=uni.getCourseHistory().findCurrentCourse(semester, professorUserID);
        
        DefaultTableModel dtm=(DefaultTableModel) tblcurrentCourse.getModel();
        dtm.setRowCount(0);
        
        if(existCourse!=null){



    //        for(course c:courseHistory.getCourseHistory()){
    //            Object[] row =new Object[3];
    //            row[0]=c;
    //            row[1]=c.getCourseName();
    //            row[2]=c.getCourseID();
    //            
    //            dtm.addRow(row);
    //        }
            ArrayList<Student> studentHistory = uni.studentHistory.getStudentHistory();
            for(Course c:uni.courseHistory.getCourseHistory()){
                if ( c.getProfessorUserID() != null) {
                    if(c.getSemester().equals(semester) && c.getProfessorUserID().equals(professorUserID)){
                        Object[] row =new Object[3];
                        row[0]=c.getCourseID();
                        row[1]=c.getCourseName();
                        Integer studentCount=0;
                        for(Student s : studentHistory){
                            Course course=s.getStudentCourse(c.getCourseID());
                            if (course !=null){
                            if (c.getCourseID().equals(course.getCourseID())){
                                studentCount++;
                            }  
                            }
                        }
                        row[2]=studentCount;


                        dtm.addRow(row);
                    }
                }
            }
        }
        else{
            dtm.setRowCount(0);
            
        }

    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSemester = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcurrentCourse = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 237, 253));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CURRENT COURSE");

        btnSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023Spring", "2023Fall" }));
        btnSemester.setSelectedIndex(-1);
        btnSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemesterActionPerformed(evt);
            }
        });

        tblcurrentCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "COURSE ID", "COURSE NAME", "NUMBER OF STUDENTS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblcurrentCourse);

        btnBack.setBackground(new java.awt.Color(237, 163, 90));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(btnSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 320, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemesterActionPerformed
        // TODO add your handling code here:
        currentCourseTable();
    }//GEN-LAST:event_btnSemesterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> btnSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcurrentCourse;
    // End of variables declaration//GEN-END:variables
}
