/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Uni.Course.Course;
import Uni.Course.CourseHistory;
import Uni.Professor.Professor;
import Uni.Uni;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ingrid
 */
public class ProfessorManageStudent2JPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private Professor professor;
    private Uni uni;
    private String semester;
    private String courseID;
    private String courseName;
    /**
     * Creates new form ProfessorManageStudent2JPanel
     */


    ProfessorManageStudent2JPanel(JPanel workArea, Professor professor,Uni uni,String semester) {
        initComponents();
        this.workArea=workArea;
        this.professor=professor;
        this.uni=uni;
        this.semester=semester;
        this.queryCourseInfo(professor.getProfessorUserID(),semester);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChooseCourse = new javax.swing.JLabel();
        cboxCourse = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 237, 253));

        lblChooseCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        lblChooseCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChooseCourse.setText("CHOOSE COURSE");

        cboxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course1", "Course 2" }));
        cboxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCourseActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(237, 163, 90));
        btnNext.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(237, 163, 90));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChooseCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cboxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack)
                .addGap(44, 44, 44)
                .addComponent(lblChooseCourse)
                .addGap(51, 51, 51)
                .addComponent(cboxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        //String course=cboCourse.getSelectedItem().toString();  
        String[] buff=cboxCourse.getSelectedItem().toString().split("-");
        courseID=buff[0];
        
        ProfessorManageStudent3JPanel panel = new ProfessorManageStudent3JPanel(workArea,professor,uni,semester,courseID);
        workArea.add("ProfessorManageStudent3JPanel",panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnNextActionPerformed

    private void cboxCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCourseActionPerformed

    private void queryCourseInfo(String professorUserid, String semester) {
        
//        String courseID;
//        String courseName;       
        ArrayList<Course> courseHistory = uni.courseHistory.getCourseHistory();
        cboxCourse.removeAllItems();
        for(Course c : courseHistory) {
            
            if (c.getProfessorUserID() != null) {
                if (c.getProfessorUserID().equals(professorUserid) &&
                    c.getSemester().equals(semester)    )  {            
                 //courseName= c.getCourseName().toString();
                 //courseID= c.getCourseID().toString();               
                this.cboxCourse.addItem(c.getCourseID() +"-"+c.getCourseName());   
                    }
             }       
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cboxCourse;
    private javax.swing.JLabel lblChooseCourse;
    // End of variables declaration//GEN-END:variables
}
