/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

//import Uni.Course.CourseHistory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Uni.Professor.Professor;
import Uni.Student.StudentHistory;
import Uni.Uni;
import javax.swing.JOptionPane;

/**
 *
 * @author sally
 */
public class ProfessorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorWorkAreaJPanel
     */
    private JPanel workArea;
    private Professor professor;
    private Uni uni;
    private StudentHistory studentHistory;
//    private CourseHistory CourseHistory;
    
    ProfessorWorkAreaJPanel(JPanel workArea, Professor professor,Uni uni)  {
        initComponents();
        this.workArea=workArea;
        this.uni=uni;
        this.professor=professor;
//        this.StudentHistory=StudentHistory;

        txtProfessorName.setText(professor.getProfessorName());
        txtProfessorID.setText(professor.getProfessorID());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRanking = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnCourse = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnSearchStudents = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtProfessorName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProfessorID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(205, 237, 253));

        btnRanking.setBackground(new java.awt.Color(237, 163, 90));
        btnRanking.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRanking.setText("STUDENT SCORE");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });

        btnManage.setBackground(new java.awt.Color(237, 163, 90));
        btnManage.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnManage.setText("MANAGE STUDENT");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(237, 163, 90));
        btnProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnProfile.setText("MY PROFILE");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnCourse.setBackground(new java.awt.Color(237, 163, 90));
        btnCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCourse.setText("CURRENT COURSE");
        btnCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseActionPerformed(evt);
            }
        });

        btnHistory.setBackground(new java.awt.Color(237, 163, 90));
        btnHistory.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnHistory.setText("STUDENT RANKING");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        lblTitle.setText("PROFESSOR");

        btnRegister.setBackground(new java.awt.Color(237, 163, 90));
        btnRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRegister.setText("REGISTER COURSE");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnSearchStudents.setBackground(new java.awt.Color(237, 163, 90));
        btnSearchStudents.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSearchStudents.setText("SEARCH STUDENT");
        btnSearchStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentsActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(153, 204, 255));
        btnLogOut.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome! Professor");

        txtProfessorName.setEditable(false);
        txtProfessorName.setEnabled(false);
        txtProfessorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Professor ID :");

        txtProfessorID.setEditable(false);
        txtProfessorID.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblTitle)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProfessorID, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnManage)
                                    .addComponent(btnSearchStudents))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHistory)
                                    .addComponent(btnRanking)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegister)
                                .addGap(89, 89, 89)
                                .addComponent(btnCourse))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProfile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogOut)))))
                .addGap(85, 85, 85))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCourse, btnHistory, btnManage, btnProfile, btnRanking, btnRegister, btnSearchStudents});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(112, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCourse, btnHistory, btnManage, btnProfile, btnRanking, btnRegister, btnSearchStudents});

    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        ProfessorProfileJPanel panel= new ProfessorProfileJPanel(workArea,professor,uni);
        workArea.add("ProfileJPanel",panel);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseActionPerformed
        // TODO add your handling code here:
        ProfessorCurrentCourseJPanel panel = new ProfessorCurrentCourseJPanel(workArea,professor,uni);
        workArea.add("CurrentClassJPanel",panel);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnCourseActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        ProfessorStudentScoreJPanel panel = new ProfessorStudentScoreJPanel(workArea,professor,uni);
        workArea.add("RankingStudentJPanel",panel);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        ProfessorStudentRanking1JPanel panel = new ProfessorStudentRanking1JPanel(workArea,professor,uni);
        workArea.add("TH1semesterJPanel",panel);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        ProfessorCourseJPanel panel = new ProfessorCourseJPanel(workArea,professor,uni);
        workArea.add("AdminCourseJPanel",panel);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        ProfessorManageStudent1JPanel panel = new ProfessorManageStudent1JPanel(workArea,professor,uni);
        workArea.add("ProfessorManageStudent1JPanel",panel);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnSearchStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentsActionPerformed
        // TODO add your handling code here:
       ProfessorSearchStudentJPanel panel = new ProfessorSearchStudentJPanel(workArea, uni);
       workArea.add("SearchStudentsJPanel",panel);
       CardLayout layout=(CardLayout) workArea.getLayout();
       layout.next(workArea);
    }//GEN-LAST:event_btnSearchStudentsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure about logging out of the system?", "Log Out Confirmation", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION){
            
            // Remove all panels from the workArea
            workArea.removeAll();
            // Repaint the workArea
            workArea.revalidate();
            workArea.repaint();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtProfessorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourse;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSearchStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtProfessorID;
    private javax.swing.JTextField txtProfessorName;
    // End of variables declaration//GEN-END:variables
}
