/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PurchasingOfficerRole;

import Hospital.Hospital;
import Hospital.Organization.StaffOrganization;
import Hospital.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author josie
 */
public class PurchasingOfficerProfileJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private UserAccount userAccount;
    private StaffOrganization organization;
    private Hospital hospital;
    /**
     * Creates new form PurchasingOfficerJPanel
     */
    
    public PurchasingOfficerProfileJPanel(JPanel workArea, UserAccount userAccount, StaffOrganization organization, Hospital hospital) {
        initComponents();
        this.workArea = workArea;
        this.userAccount = userAccount;
        this.organization = organization;
        this.hospital = hospital;
        
        setSize(1500, 1000);
        displayProfile();
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }
    
    private void displayProfile() {
        txtUsername.setText(userAccount.getUsername());
        txtPassword.setText(userAccount.getPassword());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Purchasing Officer Profile");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 117, 1488, -1));

        btnUpdate.setBackground(new java.awt.Color(102, 204, 0));
        btnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 355, 99, 46));

        btnSave.setBackground(new java.awt.Color(255, 102, 102));
        btnSave.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 355, 99, 46));

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        txtUsername.setEnabled(false);
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 210, 198, 35));

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        txtPassword.setText("jPasswordField1");
        txtPassword.setEnabled(false);
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 263, 198, 35));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Username :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Password :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 266, -1, -1));

        btnBack1.setBackground(new java.awt.Color(0, 0, 0));
        btnBack1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contract-purchasing-manager-icon-cartoon-style-vector-32104690.jpeg"))); // NOI18N
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 190, 1500, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //        displayMode(false);
        //        txtUsername.requestFocusInWindow();
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);

        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String password = txtPassword.getText();
        boolean isValidPassword = password.length() >= 8 &&
                password.matches(".*[a-z].*") &&
                password.matches(".*[A-Z].*") &&
                password.matches(".*\\d.*");
        
        if( txtUsername.getText().isEmpty() || txtPassword.getText().isEmpty() || txtUsername.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "The information isn't completed! Please check!");

        }
        else{

            // User Name validation
            String username=txtUsername.getText();
            if (organization.getUserAccountDirectory().findUserAccount(username) != null && !(userAccount.getUsername().equals(username))) {
                JOptionPane.showMessageDialog(null, "Username already exists! ");
            }
            if(!isValidPassword) {
                JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, and one digit.");
                txtPassword.setText("");
            }
            else {

                userAccount.setPassword(txtPassword.getText());
                userAccount.setUsername(username);
              
//                displayMode(true);
                JOptionPane.showMessageDialog(null,"User Information updated successfully!");

                txtUsername.setEnabled(false);
                txtPassword.setEnabled(false);

                btnSave.setEnabled(false);
                btnUpdate.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
