/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PurchasingOfficerRole;

import Hospital.Hospital;
import Hospital.PurchasingOfficer.PurchasingOfficer;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josie
 */
public class PurchaseHistoryJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Hospital hospital;
    /**
     * Creates new form PurchaseHistoryJPanel
     */

    PurchaseHistoryJPanel(JPanel userProcessContainer, Hospital hospital) {
        initComponents();
        
        setSize(1500, 1000);
        this.userProcessContainer = userProcessContainer;
        this.hospital = hospital;
        
        historyTable();
    }

    private void historyTable(){
        DefaultTableModel dtm=(DefaultTableModel) tblHistory.getModel();
        dtm.setRowCount(0);
        for(PurchasingOfficer purchasingOfficer :hospital.purchasingOfficerHistory.getPurchasingOfficerList()){
            String status=purchasingOfficer.getStatus();
            if(status=="Approved"){
                Object[] row =new Object[8];
                row[0]=purchasingOfficer.getDate();
                row[1]=purchasingOfficer.getDoctorName();
                row[2]=purchasingOfficer.getManufactureName();
                row[3]=purchasingOfficer.getProductName();
                row[4]=purchasingOfficer.getQuantity();
                row[5]=purchasingOfficer.getPrice();
                row[6]=purchasingOfficer.getMessage();
                row[7]=purchasingOfficer.getStatus();

                dtm.addRow(row);
            }
        }
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        btnBack8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Purchase History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-510, 110, 1494, -1));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tblHistory.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Doctor", "Manufacturer", "Product", "Quantity", "Price", "Message", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHistory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 171, 1345, 480));

        btnBack8.setBackground(new java.awt.Color(0, 0, 0));
        btnBack8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack8.setForeground(new java.awt.Color(255, 255, 255));
        btnBack8.setText("< Back");
        btnBack8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack8ActionPerformed(evt);
            }
        });
        add(btnBack8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 37));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/approved-credit-score-182055269-5772eb645f9b585875143864.jpeg"))); // NOI18N
        jLabel7.setToolTipText("");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1500, 1140));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack8ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistory;
    // End of variables declaration//GEN-END:variables
}
