/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorRole;

import Hospital.Appointment.AppointmentSchedule;
import Hospital.Doctor.Doctor;
import Hospital.Hospital;
import Hospital.Organization.DoctorOrganization;
import Hospital.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josie
 */
public class AppointmentScheduleJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private DoctorOrganization organization;
    private Hospital hospital;
    private UserAccount userAccount;
    private Doctor doctor;
    /**
     * Creates new form AppointmentScheduleJPanel
     */

    public AppointmentScheduleJPanel(JPanel workArea,UserAccount userAccount, DoctorOrganization organization, Hospital hospital) {
        initComponents();
        this.workArea = workArea;
        this.organization = organization;
        this.hospital = hospital;
        this.userAccount = userAccount;
        doctor=userAccount.getDoctor();
        
        setSize(1500, 1000);
        initData();
        populateTable();
    }

    public void initData() {
         String datestring;
         cboxDate.removeAllItems();
         cboxTimeSlot.removeAllItems();
         
         //Date date = new Date();
         LocalDateTime today = LocalDateTime.now(); // Today
         for (int i = 0; i < 20; i = i+1 ){
             datestring=String.format("%1$tY-%1$tm-%1$td", today.plusDays(i));
             cboxDate.addItem(datestring);
         }
         
         cboxTimeSlot.addItem("Morning Clinic");
         cboxTimeSlot.addItem("Afternoon Clinic");
         cboxTimeSlot.addItem("Night Clinic");
         
     }
     
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblScheduleTimeSlot.getModel();

        model.setRowCount(0);

        for (AppointmentSchedule schedule : hospital.getAppointmentHistory().getAppScheduleList()) {
            String doctorID = schedule.getDoctorID();
                       
            if (doctorID.equals(doctor.getDoctorID()) ) {
                Object[] row = new Object[6];
                row[0] = schedule.getScheduleDate();
                row[1] = schedule.getTimeSlot();
                row[2] = schedule.getDepartment();
                row[3] = schedule.getDoctorID();
                row[4] = Integer.toString(schedule.getAvailability());
                row[5] = schedule.getStatus();
                //row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();

                model.addRow(row);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblScheduleTimeSlot = new javax.swing.JTable();
        btnBack6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cboxDate = new javax.swing.JComboBox<>();
        cboxTimeSlot = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAvailPatient = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Time Slots");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 1500, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel1.setText("Date :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        tblScheduleTimeSlot.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        tblScheduleTimeSlot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Time Slots", "Department", "Doctor ID", "Availability", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblScheduleTimeSlot);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 505, 1187, 348));

        btnBack6.setBackground(new java.awt.Color(0, 0, 0));
        btnBack6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack6.setForeground(new java.awt.Color(255, 255, 255));
        btnBack6.setText("< Back");
        btnBack6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack6ActionPerformed(evt);
            }
        });
        add(btnBack6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 37));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        cboxDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboxTimeSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3.setText("Time Slots :");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel5.setText("Available number of Patients :");

        txtAvailPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailPatientActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(0, 153, 51));
        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAvailPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cboxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtAvailPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 530, 300));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 430, 70));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TIME400Clocks-[Converted].jpeg"))); // NOI18N
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1500, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAvailPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailPatientActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(txtAvailPatient.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "The information isn't completed! Please check!");
            txtAvailPatient.requestFocusInWindow();
        }  
        else{
          
            String scheduleDay= cboxDate.getSelectedItem().toString();
            String timeSlot=cboxTimeSlot.getSelectedItem().toString();
            
            try {
                int availability=Integer.parseInt(txtAvailPatient.getText());
                String status="Pending";

                AppointmentSchedule schedule=hospital.getAppointmentHistory().newAppSchedule(doctor.getDoctorID(), doctor.getDepartment()
                        , timeSlot, scheduleDay, availability, status);

                populateTable();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter a valid number in the available number of patients area");
                txtAvailPatient.requestFocusInWindow();
                txtAvailPatient.setText("");
            }
            
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBack6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack6ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBack6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack6;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cboxDate;
    private javax.swing.JComboBox<String> cboxTimeSlot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblScheduleTimeSlot;
    private javax.swing.JTextField txtAvailPatient;
    // End of variables declaration//GEN-END:variables
}
