/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorRole;

import Hospital.Enterprise.Manufacturer;
import Hospital.Hospital;
import Hospital.PurchasingOfficer.PurchasingOfficer;
import Hospital.UserAccount.UserAccount;
import Hospital.WorkQueue.PurchaseRequest;
import Hospital.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josie
 */
public class DInventoryJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Hospital hospital;
    UserAccount userAccount;
    /**
     * Creates new form InventoryJPanel
     */
    
    DInventoryJPanel(JPanel userProcessContainer, Hospital hospital, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.hospital = hospital;
        this.userAccount=userAccount;
        
        setSize(1500, 1000);
        currentInventoryTable();
        currentPurchaseTable();
        
//        populatePurchaseRequestTable();
    }
    
    private void currentInventoryTable(){
        DefaultTableModel dtm=(DefaultTableModel) tblInventory.getModel();
        dtm.setRowCount(0);
        for(Manufacturer manufacturer:hospital.manufacturerDirectory.getManufacturerDirectory()){
            Object[] row =new Object[3];
            row[0]=manufacturer.getManufactureName();
            row[1]=manufacturer.getProductName();
            row[2]=manufacturer.getQuantity();
//            row[2]=manufacturer.getPrice();
            
            dtm.addRow(row);
        }
    }
    
    private void currentPurchaseTable(){
        DefaultTableModel dtm=(DefaultTableModel) tblPurchaseRequest.getModel();
        dtm.setRowCount(0);
        for(PurchasingOfficer purchasingOfficer :hospital.purchasingOfficerHistory.getPurchasingOfficerList()){
            if(userAccount.getDoctor().getName().equals(purchasingOfficer.getDoctorName())){
                Object[] row =new Object[7];
                row[0]=purchasingOfficer.getDate();
                row[1]=purchasingOfficer.getManufactureName();
                row[2]=purchasingOfficer.getProductName();
                row[3]=purchasingOfficer.getQuantity();
                row[4]=purchasingOfficer.getMessage();
                row[5]=purchasingOfficer.getStatus();
                row[6]=purchasingOfficer.getResultMessage();
                dtm.addRow(row);
                
            }
        }
    }
    
    
//    public void populatePurchaseRequestTable(){
//        DefaultTableModel model = (DefaultTableModel) tblPurchaseRequest.getModel();
//        
//        model.setRowCount(0);
//        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
//            Object[] row = new Object[6];
//            row[0] = request.getRequestDate();
//            row[1] = request.getSender();
//            row[2] = request.getSender();
//            row[3] = request.getSender();
//            row[4] = request.getMessage();
//            row[5] = request.getStatus();
//            String result = ((PurchaseRequest) request).getPurchaseResult();
//            row[6] = result == null ? "Waiting" : result;
//            
//            model.addRow(row);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchaseRequest = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnMakeARequest = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPurchaseRequest.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        tblPurchaseRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Manufacturer", "Product", "Quantity", "Message", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPurchaseRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 1370, 370));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Current Inventory");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 98, 1500, -1));

        tblInventory.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Manufacturer", "Item Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblInventory);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 179, 894, 175));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Purchase Request");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 1419, -1));

        btnMakeARequest.setBackground(new java.awt.Color(51, 153, 0));
        btnMakeARequest.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnMakeARequest.setForeground(new java.awt.Color(255, 255, 255));
        btnMakeARequest.setText("Make a Request");
        btnMakeARequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeARequestActionPerformed(evt);
            }
        });
        add(btnMakeARequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 440, 263, 37));

        btnRefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 111, 37));

        btnBack6.setBackground(new java.awt.Color(0, 0, 0));
        btnBack6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack6.setForeground(new java.awt.Color(255, 255, 255));
        btnBack6.setText("< Back");
        btnBack6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack6ActionPerformed(evt);
            }
        });
        add(btnBack6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 37));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stethoscope-and-laptop-on-doctor-working-desk-P39F2UL.jpeg"))); // NOI18N
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -23, 1550, 1050));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakeARequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeARequestActionPerformed
        // TODO add your handling code here:
        RequestPurchaseJPanel rpj = new RequestPurchaseJPanel(userProcessContainer, hospital, userAccount);
        userProcessContainer.add("RequestPurchaseJPanel", rpj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMakeARequestActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        currentPurchaseTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBack6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack6;
    private javax.swing.JButton btnMakeARequest;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTable tblPurchaseRequest;
    // End of variables declaration//GEN-END:variables
}
