/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorRole;

import Hospital.Appointment.Appointment;
import Hospital.Children.Children;
import Hospital.Doctor.Doctor;
import Hospital.Enterprise.Manufacturer;
import Hospital.Hospital;
import Hospital.Organization.DoctorOrganization;
import Hospital.Parent.Parent;
import Hospital.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ingrid
 */
public class Doctordiagnosis extends javax.swing.JPanel {
    private JPanel workArea;
    private DoctorOrganization organization;
    private Hospital hospital;
    private UserAccount userAccount;
    private Doctor doctor;
    private String selectedAppID;
    private String selectedDate;
    private String selectedSsnID;
    /**
     * Creates new form Doctor diagnosis
     */
    public Doctordiagnosis(JPanel workArea,UserAccount userAccount, DoctorOrganization organization, Hospital hospital) {
        initComponents();
        this.workArea = workArea;
        this.organization = organization;
        this.hospital = hospital;
        this.userAccount = userAccount;
        doctor=userAccount.getDoctor();
        
        setSize(1500, 1000);
        populateMedicineComboBox();
        populateDateComboBox();        
        populateTable();
    }
    
    public void populateMedicineComboBox() {
         
        cboxMedicine.removeAllItems();
         
        cboxMedicine.addItem("");        
        int j=0;  
        for(Manufacturer manufacturer:hospital.manufacturerDirectory.getManufacturerDirectory()){
            String productName =manufacturer.getProductName();
            
            if (j==0)  cboxMedicine.addItem(productName);
            j++;
            boolean duplicateFlag=false;
            for (int i=0 ; i<cboxMedicine.getItemCount(); i++) {
                if (cboxMedicine.getItemAt(i).equals(productName)) {
                    duplicateFlag=true;
                    break;
                }
            } 
            if (duplicateFlag==false) {
                cboxMedicine.addItem(productName);
            }
        }
//        cboxMedicine.addItem(""); 
//        cboxMedicine.addItem("Medicine01");
//        cboxMedicine.addItem("Medicine02");
//        cboxMedicine.addItem("Medicine03");
//        cboxMedicine.addItem("Medicine04");
//        cboxMedicine.addItem("Medicine05");
     }
    
   public void populateDateComboBox() {
         
        cboxDate.removeAllItems();
         
        cboxDate.addItem("");
        
         LocalDateTime today = LocalDateTime.now(); // Today         
         for (int i = 0; i < 20; i = i+1 ){
             String datestring=String.format("%1$tY-%1$tm-%1$td", today.plusDays(i));
             cboxDate.addItem(datestring);
         }        
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPatientList.getModel();

        model.setRowCount(0);

        for (Appointment ap : hospital.getAppointmentHistory().getAppointmentList())  {
            String doctorID = ap.getDoctorID();
            String ssnID = ap.getSSNID();
            if (txtSearchSsnId.getText().isEmpty()){
                if (doctorID.equals(doctor.getDoctorID()) ) {
                    Object[] row = new Object[7];
                    row[0] = ap.getAppointmentID();
                    row[1] = ap.getSSNID();
                    row[2] = ap.getChildName();
                    row[3] = ap.getAppointmentDate();
                    row[4] = ap.getMedicine();
                    row[5] = ap.getDescription();
                    row[6] = ap.getStatus();
                    model.addRow(row);
                }
            } 
            else {
                if (doctorID.equals(doctor.getDoctorID()) && ssnID.equals(txtSearchSsnId.getText()) ) {
                    Object[] row = new Object[7];
                    row[0] = ap.getAppointmentID();
                    row[1] = ap.getSSNID();
                    row[2] = ap.getChildName();
                    row[3] = ap.getAppointmentDate();
                    row[4] = ap.getMedicine();
                    row[5] = ap.getDescription();
                    row[6] = ap.getStatus();
                    model.addRow(row);
                }
            }
            
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientList = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        txtSearchSsnId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboxMedicine = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboxDate = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnBack6 = new javax.swing.JButton();
        btnNoShowUp = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPatientList.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        tblPatientList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Role ID", "Name", "Date", "Medicine", "Description", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatientList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPatientList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 145, 1410, 280));

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 92, 38));

        txtSearchSsnId.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        add(txtSearchSsnId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 172, 45));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Role ID :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        txtDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 329, 45));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Description :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Recommended Medicine :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, -1, -1));

        cboxMedicine.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        cboxMedicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cboxMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 245, 45));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Next Appointment Date :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 720, -1, -1));

        cboxDate.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        cboxDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDateActionPerformed(evt);
            }
        });
        add(cboxDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 710, 164, 45));

        btnSubmit.setBackground(new java.awt.Color(0, 153, 51));
        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 710, 122, 49));

        btnBack6.setBackground(new java.awt.Color(0, 0, 0));
        btnBack6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack6.setForeground(new java.awt.Color(255, 255, 255));
        btnBack6.setText("< Back");
        btnBack6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack6ActionPerformed(evt);
            }
        });
        add(btnBack6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 37));

        btnNoShowUp.setBackground(new java.awt.Color(51, 51, 51));
        btnNoShowUp.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnNoShowUp.setForeground(new java.awt.Color(255, 51, 51));
        btnNoShowUp.setText("Didn't show up");
        btnNoShowUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoShowUpActionPerformed(evt);
            }
        });
        add(btnNoShowUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 450, 230, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor-pixabay_P24csjdR.jpeg"))); // NOI18N
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1500, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void cboxDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDateActionPerformed
        // TODO add your handling code here:
        if (cboxDate.getSelectedItem() != null) {
            selectedDate=cboxDate.getSelectedItem().toString();
        }
    }//GEN-LAST:event_cboxDateActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatientList.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first.","Warning",JOptionPane.WARNING_MESSAGE);
        } 
        else {
            String medicine=cboxMedicine.getSelectedItem().toString();
            String nextAppointmentDate = cboxDate.getSelectedItem().toString();
            selectedAppID = (String) tblPatientList.getValueAt(selectedRow,0);
            
            
            Appointment appointment = hospital.getAppointmentHistory().findAppointment(selectedAppID);          
            appointment.setDescription(txtDescription.getText());
            appointment.setMedicine(medicine);
            appointment.setStatus("Assessed");
            
            ArrayList<Parent> parentList = hospital.getParentHistory().getParentList();
            for (Parent p : parentList ) {
                Children c = p.getChildrenById(selectedSsnID);
                if(c != null){
                    c.setDescription(txtDescription.getText());
                    c.setPrescription(medicine);
                    c.setNextAppointment(nextAppointmentDate);
                }
            }
            
            JOptionPane.showMessageDialog(null,"The information updated successfully!");
            txtSearchSsnId.setText("");
            populateTable();
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         populateTable();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblPatientListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientListMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblPatientList.getSelectedRow();
        if(selectedRow>=0){
            selectedAppID = (String) tblPatientList.getValueAt(selectedRow,0);
            selectedSsnID = (String) tblPatientList.getValueAt(selectedRow,1);
            txtSearchSsnId.setText(selectedSsnID); 
        }
    }//GEN-LAST:event_tblPatientListMouseClicked

    private void btnBack6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack6ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBack6ActionPerformed

    private void btnNoShowUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoShowUpActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatientList.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first.","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else {

            selectedAppID = (String) tblPatientList.getValueAt(selectedRow,0);

            Appointment appointment = hospital.getAppointmentHistory().findAppointment(selectedAppID);
            appointment.setStatus("Canceled");

            JOptionPane.showMessageDialog(null,"The Appointment canceled successfully!");
            txtSearchSsnId.setText("");
            populateTable();
        }
    }//GEN-LAST:event_btnNoShowUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack6;
    private javax.swing.JButton btnNoShowUp;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cboxDate;
    private javax.swing.JComboBox<String> cboxMedicine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPatientList;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtSearchSsnId;
    // End of variables declaration//GEN-END:variables
}
