/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManufacturerEnterprise;

import Hospital.Enterprise.Manufacturer;
import Hospital.Hospital;
import Hospital.PurchasingOfficer.PurchasingOfficer;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josie
 */
public class SaleHistoryJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Hospital hospital;
    Manufacturer m;
    /**
     * Creates new form SaleHistory1JPanel
     */
    
    SaleHistoryJPanel(JPanel userProcessContainer, Hospital hospital, Manufacturer m) {
        initComponents();
        
        setSize(1500, 1000);
        this.userProcessContainer = userProcessContainer;
        this.hospital = hospital;
        this.m = m;
        
        saleTable();
    }
    
    private void saleTable(){
        DefaultTableModel dtm=(DefaultTableModel) tblSale.getModel();
        dtm.setRowCount(0);
        for(PurchasingOfficer purchasingOfficer :hospital.purchasingOfficerHistory.getPurchasingOfficerList()){
            if(m.getManufactureName().equals(purchasingOfficer.getManufactureName())){
                String status=purchasingOfficer.getStatus();
                if(status=="Approved"){
                    Object[] row =new Object[6];
                    row[0]=purchasingOfficer.getDate();
                    row[1]=purchasingOfficer.getProductName();
                    row[2]=purchasingOfficer.getQuantity();
                    row[3]=purchasingOfficer.getPrice();
                    row[4]=purchasingOfficer.getMessage();
                    row[5]=purchasingOfficer.getStatus();

                    dtm.addRow(row);
                }
                
            }
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSale = new javax.swing.JTable();
        btnBack6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sale History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, 1488, -1));

        tblSale.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        tblSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Product", "Quantity", "Price", "Message", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSale);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 202, 1310, 500));

        btnBack6.setBackground(new java.awt.Color(0, 0, 0));
        btnBack6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack6.setForeground(new java.awt.Color(255, 255, 255));
        btnBack6.setText("< Back");
        btnBack6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack6ActionPerformed(evt);
            }
        });
        add(btnBack6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 37));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etactics-inc-aaY0VzXaSiI-unsplash.jpeg"))); // NOI18N
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSale;
    // End of variables declaration//GEN-END:variables
}
