/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ParentRole;

import Hospital.Appointment.Appointment;
import Hospital.Hospital;
import Hospital.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author josie
 */
public class FeedbackJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private Appointment appointment;
    private Hospital hospital;
    private UserAccount userAccount;
    /**
     * Creates new form FeedbackJPanel
     */
    public FeedbackJPanel(JPanel workArea,UserAccount userAccount, Appointment appointment, Hospital hospital) {
        initComponents();
        
        setSize(1500, 1000);
        this.workArea = workArea;
        this.appointment = appointment;
        this.hospital = hospital;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack8 = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFeedback = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Feedback to Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-540, 180, 1488, -1));

        btnBack8.setBackground(new java.awt.Color(0, 0, 0));
        btnBack8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack8.setForeground(new java.awt.Color(255, 255, 255));
        btnBack8.setText("< Back");
        btnBack8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack8ActionPerformed(evt);
            }
        });
        add(btnBack8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 37));

        btnSend.setBackground(new java.awt.Color(0, 153, 51));
        btnSend.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 125, 48));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Content :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        txtFeedback.setColumns(20);
        txtFeedback.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        txtFeedback.setRows(5);
        jScrollPane1.setViewportView(txtFeedback);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 400, 229));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/15203103_xxl_1500x1000.jpeg"))); // NOI18N
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1500, 1140));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack8ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBack8ActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        appointment.setFeedback(txtFeedback.getText());
        appointment.setStatus("Completed");
        JOptionPane.showMessageDialog(null,"User feedback updated successfully!");
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack8;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtFeedback;
    // End of variables declaration//GEN-END:variables
}
