/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Patient;

/**
 *
 * @author sally
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    Patient patient;
    public PatientJPanel(Patient patient) {
        initComponents();
        this.patient=patient;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        lblPrimaryDoc = new javax.swing.JLabel();
        txtPrimaryDoc = new javax.swing.JTextField();
        lblonMedication = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        lbldateOfNextApp = new javax.swing.JLabel();
        txtdateOfNextApp = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        boxAllergies = new javax.swing.JComboBox<>();
        boxMedication = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Patient");

        lblPatientID.setText("Patient ID:");

        lblPrimaryDoc.setText("Primary Doctor:");

        lblonMedication.setText("Medication:");

        lblAllergies.setText("Allergies:");

        lbldateOfNextApp.setText("Date of Next Appointment (MM/DD/YYYY):");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        boxAllergies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        boxAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAllergiesActionPerformed(evt);
            }
        });

        boxMedication.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        boxMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMedicationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbldateOfNextApp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdateOfNextApp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAllergies)
                            .addComponent(lblPatientID))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(boxAllergies, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPrimaryDoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrimaryDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblonMedication)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientID)
                    .addComponent(lblPrimaryDoc)
                    .addComponent(txtPrimaryDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergies)
                    .addComponent(lblonMedication)
                    .addComponent(boxAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldateOfNextApp)
                    .addComponent(txtdateOfNextApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if(txtPatientID.getText().isEmpty() || txtPrimaryDoc.getText().isEmpty() || boxAllergies.getSelectedItem().toString().isEmpty() || boxMedication.getSelectedItem().toString().isEmpty() || txtdateOfNextApp.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Is Empty! Please check");  
        }else{
            patient.setPatientID(txtPatientID.getText());
            patient.setPrimaryDoc(txtPrimaryDoc.getText());
            patient.setAllergies(boxAllergies.getSelectedItem().toString());
            patient.setOnMedication(boxMedication.getSelectedItem().toString());
//            patient.setAllergies(txtAllergies.getText());
//            patient.setOnMedication(txtonMedication.getText());
            patient.setDateOfNextApp(txtdateOfNextApp.getText());
            JOptionPane.showMessageDialog(this, "Patient Information Saved");   
        }
        
//        patient.setPatientID(txtPatientID.getText());
//        patient.setPrimaryDoc(txtPrimaryDoc.getText());
//        patient.setAllergies(txtAllergies.getText());
//        patient.setOnMedication(txtonMedication.getText());
//        patient.setDateOfNextApp(txtdateOfNextApp.getText());
        
//        JOptionPane.showMessageDialog(this, "Patient Information Saved");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void boxAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxAllergiesActionPerformed

    private void boxMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMedicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAllergies;
    private javax.swing.JComboBox<String> boxMedication;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPrimaryDoc;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbldateOfNextApp;
    private javax.swing.JLabel lblonMedication;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPrimaryDoc;
    private javax.swing.JTextField txtdateOfNextApp;
    // End of variables declaration//GEN-END:variables
}
